name: Publish Besom core and providers to GitHub Packages

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: packages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  delete-core-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: delete
    strategy:
      matrix:
        package-name:
          - 'org.virtuslab.besom-json_3'
          - 'com.virtuslab.besom-core_3'
          - 'com.virtuslab.besom-cats_3'
          - 'com.virtuslab.besom-zio_3'
          - 'org.virtuslab.besom-codegen_3'
          - 'org.virtuslab.besom-compiler-plugin_3'
    steps:
      - uses: actions/delete-package-versions@v5.0.0
        with:
          min-versions-to-keep: 0
          package-name: {{ matrix.package-name }}
          package-type: maven

  publish-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
        just-version: '1.14.0' # just for sanity
      - uses: coursier/cache-action@v6.4.3
      - uses: VirtusLab/scala-cli-setup@v1.1.0
        with:
          jvm: graalvm-java11:22.3.1
          power: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Publish Besom
        run: |-
          just publish-gh-all
      - name: Upsert GitHub release
        run: |-
          just upsert-gh-release
      - name: Publish language plugins
        run: |-
          just publish-language-plugins-all

  publish-provider:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        provider:
          - aws
          - azure
          - docker
          - gcp
          - kubernetes
          - random
          - tls
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0' # just for sanity
      - uses: coursier/cache-action@v6.4.3
      - uses: VirtusLab/scala-cli-setup@v1.1.0
        with:
          jvm: graalvm-java11:22.3.1
          power: true
      - uses: actions/delete-package-versions@v5.0.0
        with:
          min-versions-to-keep: 0
          package-name: com.virtuslab.besom-{{ matrix.provider }}_3
          package-type: maven
      - name: Publish providers
        run: |-
          just cli packages metadata {{ matrix.provider }}
          just cli packages generate {{ matrix.provider }}
          just cli packages publish-github {{ matrix.provider }}
