name: Templates smoke tests

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'develop' ]
    paths:
      - 'templates/**'
  pull_request:
    branches: [ 'main', 'develop' ]
    paths:
      - 'templates/**'

env:
  PULUMI_CONFIG_PASSPHRASE: 'passphrase'
  PULUMI_SKIP_UPDATE_CHECK: 'true'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    if: "! github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0' # just for sanity
      - uses: pulumi/actions@v4
        with:
          pulumi-version: '3.94.2'
      - uses: coursier/cache-action@v6.4.3
      - uses: VirtusLab/scala-cli-setup@v1.1.0
        with:
          jvm: graalvm-java11:22.3.1
          power: true
      - name: Login in to pulumi
        run: pulumi login --local
      - name: Test templates
        run: |-
          scala-cli --power config repositories.credentials maven.pkg.github.com env:GITHUB_ACTOR env:GITHUB_TOKEN
          just test-templates
