on:
  push:
    branches: [ 'main', 'develop' ]
    paths:
      - 'templates'
  pull_request:
    branches: [ 'main', 'develop' ]
    paths:
      - 'templates'

env:
  PULUMI_CONFIG_PASSPHRASE: 'passphrase'

jobs:
  preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0' # just for sanity
      - uses: pulumi/actions@v4
        with:
          pulumi-version: '3.86.0'
      - uses: coursier/cache-action@v6.4.3
      - uses: VirtusLab/scala-cli-setup@v1.0.4
        with:
          jvm: 11
          power: true
      - name: Login in to pulumi
        run: pulumi login --local
      - name: Test templates
        run: just test-templates