name: Verify upstream protobuf compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  verify-pulumi-protos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v1
      with:
        just-version: '1.14.0' # just for sanity
    - uses: coursier/cache-action@v6.4.3
    - uses: VirtusLab/scala-cli-setup@v1.1.0
      with: 
        jvm: graalvm-java11:22.3.1
        power: true
    - uses: arduino/setup-protoc@v1

    - name: Fetch & generate protobuf 
      run: |-
        scala-cli --power config repositories.credentials maven.pkg.github.com env:GITHUB_ACTOR env:GITHUB_TOKEN
        just cli proto all

    - name: Compile SDK with rebuilt protobufs
      run: just compile-sdk